DemoSanBong/Models/Field.cs
using NuGet.Protocol;
using System.ComponentModel.DataAnnotations;

namespace DemoSanBong.Models
{
    public class Field
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name ="Mã sân")]
        public string Name { get; set; }

        [Required,Display(Name ="Loại sân")]
        public string Type { get; set; }

        [Display(Name = "Mô tả sân")]
        public string? Description { get; set; }

        public bool IsActive { get; set; }//hoạt động/bảo trì

        public string? ImagePath { get; set; }

        public double getCurrentPrice(AppDbContext context) //Lấy giá giờ hiện tại
        {
            var f = context.FieldRates.Where(i=>i.FieldId == Id&&i.EffectiveDate<DateTime.Now&&i.Type==0).OrderByDescending(i=>i.EffectiveDate).FirstOrDefault();
            if (f == null) return 0;
            return f.Price;
        }
        public double GetCurrentPricePerMonth(AppDbContext context)// giá tháng hiện tại
        {
            var f = context.FieldRates.Where(i => i.FieldId == Id && i.EffectiveDate < DateTime.Now && i.Type == 1).OrderByDescending(i => i.EffectiveDate).FirstOrDefault();
            if (f == null) return 0;
            return f.Price;
        }
        public double GetPrice(AppDbContext context, DateTime date)// tra giá tại một thời điểm
        {
            var f = context.FieldRates.Where(i => i.FieldId == Id && i.EffectiveDate < date && i.Type == 0).OrderByDescending(i => i.EffectiveDate).FirstOrDefault();
            if (f == null) return 0;
            return f.Price;
        }
        public double GetPricePerMonth(AppDbContext context, DateTime date) //tra giá tháng thại thời điểm
        {
            var f = context.FieldRates.Where(i => i.FieldId == Id && i.EffectiveDate < date && i.Type == 1).OrderByDescending(i => i.EffectiveDate).FirstOrDefault();
            if (f == null) return 0;
            return f.Price;
        }

        public List<FieldImage>? images(AppDbContext context)
        {
            var list = context.FieldImages.Where(i => i.FieldId == Id).ToList();
            return list;
        }
    }
}

DemoSanBong/ViewModels/FieldView.cs
using DemoSanBong.Models;

namespace DemoSanBong.ViewModels
{
    public class FieldView
    {
        public Field Field { get; set; }
        public string Status { get; set; }
        public string StatusColor { get; set; }
        public Booking Booking { get; set; }
        public Invoice Invoice { get; set; }
    }
}

DemoSanBong/ViewModels/FieldViewModel.cs
using DemoSanBong.Models;
using System.ComponentModel.DataAnnotations;

namespace DemoSanBong.ViewModels
{
    public class FieldViewModel
    {
        public int? Id { get; set; }

        [Display(Name = "Mã sân")]
        public string Name { get; set; }

        [Display(Name = "Mô tả sân")]
        public string Description { get; set; }

        [Required, Display(Name = "Loại sân")]
        public string Type { get; set; }

        [Display(Name = "Giá giờ")]
        public double Price { get; set; }

        public double? Cost { get; set; }

        [Display(Name = "Giá tháng")]
        public double PricePerMonth { get; set; }

        [Display(Name = "Trạng thái")]
        public bool IsActive { get; set; }

        [Display(Name = "Ảnh mặc định")]
        public string? DefaultImage { get; set; }

        public DateTime? Start { get; set; }
        public DateTime? End { get; set; }

        private List<string> images;

        public void SetImages(List<string> images)
        {
            this.images = images;
        }
        public List<string> GetImages() { return images; }
    }
}

DemoSanBong/Controllers/FieldController.cs
using DemoSanBong.Models;
using DemoSanBong.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;


namespace DemoSanBong.Controllers
{
    public class FieldController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly AppDbContext _context;
        public FieldController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        //trang list sân
        public IActionResult Index()
        {
            var fields = _context.Fields.ToList();
            var models = new List<FieldViewModel>();
            foreach (var f in fields)
            {
                var item = new FieldViewModel
                {
                    Id = f.Id,
                    Name = f.Name,
                    Type = f.Type,
                    Price = f.getCurrentPrice(_context),
                    PricePerMonth = f.GetCurrentPricePerMonth(_context),
                    Description = f.Description,
                    IsActive = f.IsActive,
                };
                var img = _context.FieldImages.FirstOrDefault(i => i.FieldId == f.Id && i.IsDefault == true);
                if (img != null)
                {
                    item.DefaultImage = f.ImagePath + img.FileName;
                }
                models.Add(item);
            }
            return View(models);
        }

        public IActionResult Create()
        {
            return View(new FieldViewModel());
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(FieldViewModel model, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                //Kiểm tra trùng tên
                var field = _context.Fields.FirstOrDefault(i => i.Name == model.Name);
                if (field != null)
                {
                    ModelState.AddModelError(string.Empty, "Tên phòng đã tồn tại");
                    return View(field);
                }
                field = new Field
                {
                    Name = model.Name,
                    Description = model.Description,
                    Type = model.Type,
                    IsActive = model.IsActive,
                };
                _context.Fields.Add(field);
                await _context.SaveChangesAsync();

                //lưu path ảnh
                field.ImagePath = "Images/FieldImages/";
                _context.Fields.Update(field);
                await _context.SaveChangesAsync();
                //thêm giá sân
                _context.FieldRates.AddRange(
                    new FieldRate
                    {
                        FieldId = field.Id,
                        Price = model.Price,
                        Type = 0,
                        EffectiveDate = DateTime.Now
                    },
                    new FieldRate
                    {
                        FieldId = field.Id,
                        Price = model.PricePerMonth,
                        Type = 1,
                        EffectiveDate = DateTime.Now
                    });
                await _context.SaveChangesAsync();

                //Tạo folder 
                string fieldFolder = Path.Combine(_webHostEnvironment.WebRootPath, "Images", "FieldImages");
                if (!Directory.Exists(fieldFolder))
                {
                    Directory.CreateDirectory(fieldFolder);
                }
                //Lấy tên file
                string fileName = Guid.NewGuid().ToString() + "-" + image.FileName;

                //lấy đường dẫn folder ảnh
                string filePath = Path.Combine(fieldFolder, fileName);

                //Lưu ảnh vào folder
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await image.CopyToAsync(fileStream);
                }

                //cập nhật đường dẫn ảnh sân


                var fieldImage = new FieldImage
                {
                    FieldId = field.Id,
                    IsDefault = true,
                    FileName = fileName,
                };
                _context.FieldImages.Add(fieldImage);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, "Hãy upload ảnh!");
            return View(model);
        }
        public IActionResult Detail(int id)
        {
            var field = _context.Fields.FirstOrDefault(f => f.Id == id);
            if (field == null)
                return NotFound();
            return View(field);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var field = _context.Fields.Find(id);
            if (field == null)
                return NotFound();
            _context.Fields.Remove(field);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var field = _context.Fields.Find(id);
            if (field == null)
                return NotFound();
            FieldViewModel model = new FieldViewModel
            {
                Id = field.Id,
                Name = field.Name,
                Description = field.Description,
                Type = field.Type,
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(FieldViewModel model)
        {
            var field = _context.Fields.FirstOrDefault(i => i.Id == model.Id);
            if (field == null)
                return NotFound();
            field.Name = model.Name;
            field.Description = model.Description;
            field.Type = model.Type;
            _context.Fields.Update(field);
            await _context.SaveChangesAsync();
            return RedirectToAction("Detail", new { id = model.Id });
        }



        [Authorize(Roles = "Cashier")]
        public IActionResult Status()
        {
            var fields = _context.Fields.ToList();
            var models = new List<FieldView>();
            foreach (var field in fields)
            {
                var model = new FieldView
                {
                    Field = field,
                    Status = "Trống",
                    StatusColor = "btn btn-success"
                };
                models.Add(model);
            }
            var now = DateTime.Now;
            var begin = now.AddMinutes(-5);
            var end = now.AddMinutes(0);
            var bkdt = _context.BookingDetails.Where(i =>
                    (i.StartTime <= begin && i.EndTime >= end) ||
                    (i.StartTime <= begin && i.EndTime >= end) ||
                    (i.StartTime >= begin && i.EndTime <= end)).Include(i => i.Booking).ToList();

            var bks = bkdt.Where(i => i.Booking.Status ==1||i.Booking.Status==2).ToList();
            foreach (var i in bks)
            {
                if (models.Any(x => x.Field.Id == i.FieldId))
                {
                    var f = models.FirstOrDefault(x => x.Field.Id == i.FieldId);
                    f.Status = "Đã đặt";
                    f.StatusColor = "btn btn-warning";
                    f.Booking = i.Booking;
                }
            }

            var ivs = _context.Invoices.Where(i => i.Status == 0).Include(i => i.Booking).ToList();
            var bkdt2 = new List<BookingDetail>();
            foreach (var i in ivs)
            {
                var dt = _context.BookingDetails.Where(x => x.BookingId == i.BookingId).Include(a => a.Booking).FirstOrDefault();
                bkdt2.Add(dt);
            }
            var bkdt3 = bkdt2.Where(i =>
                    (i.StartTime <= begin && i.EndTime >= end) ||
                    (i.StartTime <= begin && i.EndTime >= end) ||
                    (i.StartTime >= begin && i.EndTime <= end)).ToList();

            foreach (var i in bkdt3)
            {
                if (models.Any(x => x.Field.Id == i.FieldId))
                {
                    var f = models.FirstOrDefault(x => x.Field.Id == i.FieldId);
                    f.Status = "Đang đá";
                    f.StatusColor = "btn btn-danger";
                    f.Invoice = ivs.FirstOrDefault(a => a.BookingId == i.Booking.Id);
                }
            }
            return View(models);
        }
    }
}

DemoSanBong/Views/Field/Create.cshtml
@model DemoSanBong.ViewModels.FieldViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<link rel="stylesheet" href="~/css/cField.css" />

<h1 style="text-align: center; margin-bottom: 20px;">Explore Our <span class="highlight" style="color: #ffb400;">CREATE FIELD</span></h1>

<form asp-action="Create" asp-controller="Field" enctype="multipart/form-data" id="createForm" class="field-container">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="field-left">
        <div class="image-grid">
            <div class="form-img">
                <label asp-for="DefaultImage">Upload Image</label>
                <input type="file" name="image" class="form-control" id="imageUpload" />
            </div>
            <div class="form-img">
                <img id="Image" src="~/Images/default.jpg" alt="No Image" />
            </div>
        </div>
    </div>
    <div class="field-right">
        <div class="form-container">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>

                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>

                <label asp-for="PricePerMonth" class="control-label"></label>
                <input asp-for="PricePerMonth" class="form-control" />
                <span asp-validation-for="PricePerMonth" class="text-danger"></span>
            </div>
            <div class="form-group full-width">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group-other" style="margin-bottom: 15px">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> Kích hoạt ngay
                </label>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" class="btn btn-primary">LƯU</button>
            </div>

        </div>

        <div>
            <a class="text-warning" asp-action="Index" style="padding-left: 35px;">Quay lại</a>
        </div>
    </div>
</form>

@section Scripts {
    <script>
        document.getElementById('imageUpload').addEventListener('change', function (event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('Image');
                output.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
        });
    </script>
}

DemoSanBong/Views/Field/Index.cshtml
@model IEnumerable<DemoSanBong.ViewModels.FieldViewModel>

@{
    ViewData["Title"] = "Index";
}
<link rel="stylesheet" href="~/css/iField.css"/>

<h1>Explore Our <span class="highlight">FIELDS</span></h1>

<div class="container">
    <p>
        <a asp-action="Create" style="margin-left: 10px">Create New</a>
    </p>
    <div class="field-grid">
        @foreach (var item in Model)
        {
            <div class="field-card">
                <div class="field-info">
                    @if(item.Type=="5 người")
                    {
                        
                        <img src="~/Images/2nd.jpg" alt="@item.Name" />
                    }
                    else if(item.Type=="7 người")
                    {
                        <img src="~/Images/3th.jpg" alt="@item.Name" />
                    }
                    else
                    {
                        <img src="~/Images/default.jpg" alt="@item.Name" />
                    }
                    <h2>Mã Sân: @Html.DisplayFor(modelItem => item.Name) </h2>
                    <p>Mô tả sân: @Html.DisplayFor(modelItem => item.Description) </p>
                    <p>Loại sân: @Html.DisplayFor(modelItem => item.Type)</p>
                    <p>Giá Giờ: @string.Format("{0:#,0} đ",item.Price) </p>
                    <p>Giá Tháng:  @string.Format("{0:#,0} đ", item.PricePerMonth) </p>
                    
                    <div class="actions">
                        <a asp-action="Booking" asp-controller="Booking" asp-route-id="@item.Id">Đặt ngay</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Chi tiết</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

DemoSanBong/Views/Field/Status.cshtml
@model IEnumerable<DemoSanBong.ViewModels.FieldView>

@{
    ViewData["Title"] = "Status";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<style>
    .card {
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        border: 1px solid #ddd;
    }

    .item-container {
        position: relative;
    }

    .image-container {
        position: relative;
        display: inline-block;
    }

    .box {
        position: absolute;
        top: 5px;
        right: 5px;
        padding: 5px 10px;
        border-radius: 5px;
        color: white;
        font-weight: bold;
    }

    .img {
        width: 100%;
        height: auto;
    }

    .my-div {
        color: #ffff
    }
</style>
<h1 style="text-align:center">Tình trạng sân</h1>
<a class="btn btn-primary" style="margin-top:20px;margin-left:50px" asp-action="Status">Refresh</a>
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-4 col-md-3 col-lg-3 item-container" style="padding: 20px">
                <div class="image-container card">
                    <img class="img-fluid" src="~/Images/FieldImages/00000000-0000-0000-0000-000000000000-3th.jpg" alt="">
                    @if (item.Status == "Đã đặt")
                    {
                        <a class=" box @item.StatusColor" style="margin:5px;" asp-action="check" asp-controller="invoice" asp-route-id="@item.Booking?.Id">
                            @item.Status
                        </a>
                    }
                    else if (item.Status == "Trống")
                    {
                        <div class=" box @item.StatusColor" style="margin:5px;">
                            @item.Status
                        </div>
                    }
                    else
                    {
                        <a class=" box @item.StatusColor" style="margin:5px;" asp-action="details" asp-controller="invoice" asp-route-id="@item.Invoice?.Id">
                            @item.Status
                        </a>
                    }
                    <div class="text-center my-div" style="background: orange">
                        <h4>@Html.DisplayFor(modelItem => item.Field.Name)</h4>
                    </div>
                </div>
            </div>

        }
    </div>
</div>