DemoSanBong/Models/Invoice.cs
using System.ComponentModel.DataAnnotations;

namespace DemoSanBong.Models
{
    public class Invoice
    {
        [Key, Display(Name = "Mã hóa đơn")]
        public int Id { get; set; }

        [Display(Name = "Ngày tạo")]
        public DateTime CreateDate { get; set; }

        [Display(Name = "Ngày nhận")]
        public DateTime CheckinDate { get; set; }

        [Display(Name = "Ngày trả")]
        public DateTime? CheckoutDate { get; set; }

        [Display(Name = "Tổng cộng")]
        public double Amount { get; set; }

        [Display(Name = "Hình thức thanh toán")]
        public int PaymentMethod { get; set; }

        [Display(Name = "Trạng thái")]
        public int Status { get; set; }

        [Display(Name ="Mã đặt sân")]
        public int BookingId { get; set; }
        public Booking Booking { get; set; }


        public string CashierId { get; set; }
        public AppUser Cashier { get; set; }

        public int VAT { get; set; }
        public string? Note { get; set; }

        public static readonly int CheckedIn = 0; //đã nhận sân
        public static readonly int CheckedOut = 1; //chưa thanh toán
        public static readonly int Paid = 2;//đã thanh toán

    }
}

DemoSanBong/ViewModels/InvoiceViewModel.cs
using DemoSanBong.Models;
using System.ComponentModel.DataAnnotations;

namespace DemoSanBong.ViewModels
{
    public class InvoiceViewModel
    {
        [Display(Name = "Mã hóa đơn")]
        public int? Id { get; set; }

        [Display(Name = "Ngày tạo")]
        public DateTime? CreateDate { get; set; }

        [Display(Name = "Ngày nhận dự kiến")]
        public DateTime? CheckinDate { get; set; }

        [Display(Name = "Ngày trả dự kiến")]
        public DateTime? CheckoutDate { get; set; }

        [Display(Name = "Tổng cộng")]
        public double? Amount { get; set; }

        public double? Deposit { get; set; }

        public double? Final {  get; set; }

        [Display(Name = "Hình thức thanh toán")]
        public int? PaymentMethod { get; set; }

        [Display(Name = "Trạng thái")]
        public int Status { get; set; }

        [Display(Name = "Mã đặt sân")]
        public Booking Booking { get; set; }

        public AppUser? Cashier { get; set; }

        public string? Note { get; set; }

        public List<FieldViewModel>? Fields { get; set; }

        public List<ServiceView>? Services { get; set; }

        public List<InvoiceServiceView>? Order {  get; set; }

        public string State
        {
            get
            {
                switch (Status)
                {
                    case 0: return "Đã nhận sân";
                    case 1: return "Chưa thanh toán";
                    default: return "Đã thanh toán";
                }
            }
        }
        public string Paymethod
        {
            get
            {
                switch (PaymentMethod)
                {
                    case 0: return "Tiền mặt";
                    case 1: return "VnPay";
                    default: return "Momo";
                }
            }
        }
    }
}

DemoSanBong/Controllers/InvoiceController.cs
using DemoSanBong.Models;
using DemoSanBong.Services;
using DemoSanBong.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Data;

namespace DemoSanBong.Controllers
{
    public class InvoiceController : Controller
    {
        #region field and Constructor
        private readonly UserManager<AppUser> _userManager;
        private readonly AppDbContext _context;
        private InvoiceViewModel currentInvoice;
        private readonly IVnPayService _vnPayService;
        private readonly IMomoService _momoService;
        public InvoiceController(IMomoService momoService, UserManager<AppUser> userManager, AppDbContext context, IVnPayService vnPayService)
        {
            _userManager = userManager;
            _context = context;
            _vnPayService = vnPayService;
            _momoService = momoService;
        }
        #endregion

        #region Xem đặt sân
        // danh sách đặt sân
        public IActionResult Index()
        {
            var list = _context.Bookings.ToList();
            var models = new List<BookingViewModel>();
            foreach (var booking in list)
            {
                models.Add(new BookingViewModel
                {
                    Id = (int)booking.Id,
                    CheckinDate = booking.CheckinDate,
                    CheckoutDate = booking.CheckoutDate,
                    Deposit = booking.Deposit,
                    Customer = _context.Users.FirstOrDefault(i => i.Id == booking.CusID),
                    RentalType = booking.RentalType,
                    Status = booking.Status,
                    CreateDate = booking.CreateDate
                });
            }
            return View(models);
        }
        //kiểm tra đặt sân
        public IActionResult Check(int id)
        {
            var booking = _context.Bookings.FirstOrDefault(i => i.Id == id);
            if (booking == null) return NotFound();
            var model = new BookingViewModel
            {
                Id = (int)booking.Id,
                CheckinDate = booking.CheckinDate,
                CheckoutDate = booking.CheckoutDate,
                Deposit = booking.Deposit,
                Customer = _context.Users.FirstOrDefault(i => i.Id == booking.CusID),
                RentalType = booking.RentalType,
                Status = booking.Status
            };
            var fields = _context.BookingDetails.Where(i => i.BookingId == id).ToList();
            model.SelectedFields = new SelectedFieldsViewModel
            {
                SelectedFields = new List<FieldViewModel>()
            };
            foreach (var item in fields)
            {
                var field = _context.Fields.FirstOrDefault(i => i.Id == item.FieldId);
                var modelfield = new FieldViewModel
                {
                    Id = field.Id,
                    Type = field.Type,
                    Name = field.Name,
                    Start = item.StartTime,
                    End = item.EndTime,
                    Price = (booking.RentalType == 0) ? field.GetPrice(_context, booking.CreateDate) : field.GetPricePerMonth(_context, booking.CreateDate)
                };
                model.SelectedFields.SelectedFields.Add(modelfield);
            }
            return View(model);
        }
        #endregion

        #region Phiếu nhận sân

        [Authorize(Roles = "Cashier")]
        public async Task<IActionResult> Checkin(int id)
        {
            var booking = _context.Bookings.Find(id);
            if (booking == null || booking.Status == 3 || booking.Status == 4)
                return NotFound();
            var cashier = await _userManager.GetUserAsync(HttpContext.User);
            var invoice = new Invoice
            {
                BookingId = booking.Id,
                CreateDate = DateTime.Now,
                CheckinDate = DateTime.Now,
                CheckoutDate = null,
                CashierId = cashier.Id,
                VAT = 10
            };
            booking.Status = 4;
            booking.CheckinDate = DateTime.Now;
            _context.Update(booking);
            _context.Invoices.Add(invoice);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id = invoice.Id });
        }
        public async Task<IActionResult> Details(int id, string? message)
        {
            var inv = _context.Invoices.Find(id);
            if (inv == null)
                return NotFound();
            currentInvoice = await GetInvoiceFromSession(id);
            ViewBag.Message = message;
            return View(currentInvoice);
        }
        public IActionResult InvoiceList(int? status)
        {
            var list = _context.Invoices.Include(i=>i.Booking).ThenInclude(i=>i.Customer).Include(i=>i.Cashier).ToList();
            if (status != null)
            {
                list = list.FindAll(i => i.Status == status);
            }
            return View(list);
        }
        #endregion

        #region Session
             /////////Sesstion
        private async Task<InvoiceViewModel> GetInvoiceFromSession(int id)
        {
            var InvoiceJson = HttpContext.Session.GetString("CurrentInvoice");
            InvoiceViewModel model;
            var inv = _context.Invoices.Find(id);
            if (string.IsNullOrEmpty(InvoiceJson))
            {
                model = new InvoiceViewModel
                {
                    Id = id,
                    CreateDate = inv.CreateDate,
                    CheckinDate = inv.CheckinDate,
                    CheckoutDate = inv.CheckoutDate,
                    Note = inv.Note,
                    Status = inv.Status
                };
                var ivsv = _context.InvoiceServices.Where(i => i.InvoiceId == id).Include(i => i.Service).ToList();
                model.Order = new List<InvoiceServiceView>();
                foreach (var i in ivsv)
                {
                    model.Order.Add(new InvoiceServiceView
                    {
                        InvoiceService = i,
                        Price = i.Service.getPrice(_context, DateTime.Now)
                    });
                }

                model.Booking = _context.Bookings.Find(inv.BookingId);
                model.Booking.Customer = _context.Users.Find(inv.Booking.CusID);
                model.Cashier = _context.Users.FirstOrDefault(i => i.Id == inv.CashierId);
                var bkDetail = _context.BookingDetails.Where(i => i.BookingId == inv.BookingId).ToList();
                model.Fields = new List<FieldViewModel>();
                foreach (var item in bkDetail)
                {
                    var field = _context.Fields.FirstOrDefault(i => i.Id == item.FieldId);
                    var modelfield = new FieldViewModel
                    {
                        Id = field.Id,
                        Type = field.Type,
                        Name = field.Name,
                        Start = item.StartTime,
                        End = item.EndTime,
                        Price = (model.Booking.RentalType == 0) ? field.GetPrice(_context, model.Booking.CreateDate) : field.GetPricePerMonth(_context, model.Booking.CreateDate)
                    };
                    if (model.Booking.RentalType == 0)
                    {
                        int stay = modelfield.End.Value.Hour - modelfield.Start.Value.Hour;
                        modelfield.Cost = stay * modelfield.Price;
                    }
                    else
                    {
                        int stay = CalculateMonthsDifference((DateTime)modelfield.Start, (DateTime)modelfield.End);
                        modelfield.Cost = stay * modelfield.Price;
                    }
                    model.Fields.Add(modelfield);
                }


                ///
                var svs = _context.Services.ToList();
                model.Services = new List<ServiceView>();
                foreach (var sv in svs)
                {
                    var svv = new ServiceView
                    {
                        Service = sv,
                        Price = sv.getPrice(_context, DateTime.Now)
                    };
                    model.Services.Add(svv);
                }

                model.Booking = _context.Bookings.Find(inv.BookingId);
                model.Booking.Customer = _context.Users.Find(model.Booking.CusID);
                model.Cashier = await _userManager.GetUserAsync(HttpContext.User);

                ////
                inv.Amount = 0;
                foreach (var i in model.Fields)
                {
                    if (model.Booking.RentalType == 0)
                    {
                        int stay = i.End.Value.Hour - i.Start.Value.Hour;
                        inv.Amount += i.Price * stay;
                    }
                    else
                    {
                        int stay = CalculateMonthsDifference(i.Start.Value, i.End.Value);
                        inv.Amount += i.Price * stay;
                    }
                }
                foreach (var i in model.Order)
                {
                    inv.Amount += i.Price * i.InvoiceService.Quantity;
                }

                model.Amount = inv.Amount;

                model.Final = inv.Amount - model.Booking.Deposit;

                _context.Invoices.Update(inv);
                _context.SaveChanges();
                return model;
            }
            model = JsonConvert.DeserializeObject<InvoiceViewModel>(InvoiceJson);
            if (model.Id != id)
            {
                model = new InvoiceViewModel
                {
                    Id = id,
                    CreateDate = inv.CreateDate,
                    CheckinDate = inv.CheckinDate,

DemoSanBong/Views/Invoice/Check.cshtml
@model DemoSanBong.ViewModels.BookingViewModel

@{
    ViewData["Title"] = "Check";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<style>
    .card {
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        border: 1px solid #ddd;
    }
</style>
@if (Model.Status == 1 || Model.Status == 2)
{
    <a onclick="confirm('Xác nhận lập phiếu')" style="margin-left:50px" class="btn btn-success" asp-action="Checkin" asp-controller="Invoice" asp-route-id="@Model.Id">Lập phiếu nhận sân</a>
}
<div class="container-fluid px-5 mt-4">
    <div class="card shadow-sm border-primary">
        <div class="card-header bg-success text-white">
            <h5 class="mb-0">Thông tin đặt sân</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <dl class="row">
                        <dt class="col-sm-6 font-weight-bold">
                            Mã đặt sân
                        </dt>
                        <dd class="col-sm-6">
                            @Html.DisplayFor(model => model.Id)
                        </dd>
                        <dt class="col-sm-6 font-weight-bold">
                            @Html.DisplayNameFor(model => model.RentalType)
                        </dt>
                        <dd class="col-sm-6">
                            @Html.DisplayFor(model => model.Type)
                        </dd>
                        <dt class="col-sm-6 font-weight-bold">
                            @Html.DisplayNameFor(model => model.CheckinDate)
                        </dt>
                        <dd class="col-sm-6">
                            @Html.DisplayFor(model => model.CheckinDate)
                        </dd>
                        <dt class="col-sm-6 font-weight-bold">
                            @Html.DisplayNameFor(model => model.CheckoutDate)
                        </dt>
                        <dd class="col-sm-6">
                            @Html.DisplayFor(model => model.CheckoutDate)
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row">
                        <dt class="col-sm-6 font-weight-bold">
                            @Html.DisplayNameFor(model => model.Deposit)
                        </dt>
                        <dd class="col-sm-6">
                            @string.Format("{0:#,0} đ", Model.Deposit)
                        </dd>
                        <dt class="col-sm-6 font-weight-bold">
                            Trạng thái
                        </dt>
                        <dd class="col-sm-6">
                            <span class="@Model.TextColor font-weight-bold">@Model.State</span>
                        </dd>
                        <dt class="col-sm-6 font-weight-bold">
                            Tên khách hàng
                        </dt>
                        <dd class="col-sm-6">
                            @Html.DisplayFor(model => model.Customer.FullName)
                        </dd>
                        <dt class="col-sm-6 font-weight-bold">
                            Số điện thoại
                        </dt>
                        <dd class="col-sm-6">
                            @Html.DisplayFor(model => model.Customer.PhoneNumber)
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="Fields" class="container-fluid px-5 mt-4">
    <div class="card shadow-sm border-primary">
        <div class="card-header bg-success text-white">
            <h5 class="mb-0">Sân đã đặt</h5>
        </div>
        <div class="card-body">
            <table class="table table-striped table-bordered">
                <thead class="bg-light text-primary">
                    <tr>
                        <th>Tên sân</th>
                        <th>Loại sân</th>
                        <th>Giá đặt sân</th>
                        <th>Bắt đầu</th>
                        <th>Kết thúc</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.SelectedFields.SelectedFields)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Name)</td>
                            <td>@Html.DisplayFor(modelItem => item.Type)</td>
                            <td>
                                @string.Format("{0:#,0}", item.Price)
                                @if (Model.RentalType == 0)
                                {
                                    @: đ/giờ
                                }
                                else
                                {
                                    @: đ/Tháng
                                }
                            </td>
                            <td>@item.Start</td>
                            <td>@item.End</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

DemoSanBong/Views/Invoice/Checkout.cshtml
@model DemoSanBong.ViewModels.InvoiceViewModel

@{
    ViewData["Title"] = "Checkout";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="container-fluid px-5 mt-4">
    <div class="card shadow-sm border-primary">
        <div class="card-header bg-success text-white">
            <h4 class="mb-0">Thông tin hóa đơn</h4>
        </div>
        <div class="card-body">
            <p class="lead mb-4">Mã số: <span class="font-weight-bold text-primary">@Model.Id</span></p>
            <hr />
            <div class="row">
                <div class="col-md-6">
                    <dl class="row">
                        <dt class="col-sm-4 font-weight-bold">Mã đặt sân</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Booking.Id)</dd>
                        <dt class="col-sm-4 font-weight-bold">Khách hàng</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Booking.Customer.FullName)</dd>
                        <dt class="col-sm-4 font-weight-bold">Số điện thoại</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Booking.Customer.PhoneNumber)</dd>
                        <dt class="col-sm-4 font-weight-bold">Ngày tạo</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.CreateDate)</dd>
                        <dt class="col-sm-4 font-weight-bold">Thời gian nhận</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.CheckinDate)</dd>
                        <dt class="col-sm-4 font-weight-bold">Thời gian trả</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.CheckoutDate)</dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row">
                        <dt class="col-sm-4 font-weight-bold">Tổng thanh toán</dt>
                        <dd class="col-sm-8">@string.Format("{0:#,0} đ", Model.Amount)</dd>
                        <dt class="col-sm-4 font-weight-bold">Đã đặt cọc</dt>
                        <dd class="col-sm-8">@string.Format("{0:#,0} đ", Model.Booking.Deposit)</dd>
                        <dt class="col-sm-4 font-weight-bold">Còn lại</dt>
                        <dd class="col-sm-8">@string.Format("{0:#,0} đ", Model.Final)</dd>
                        <dt class="col-sm-4 font-weight-bold">Hình thức thanh toán</dt>
                        <dd class="col-sm-8">
                            <div class="form-check">
                                <input type="radio" name="PaymentMethod" value="0" id="paymentCash" checked class="form-check-input">
                                <label class="form-check-label" for="paymentCash">Tiền mặt</label>
                            </div>
                            <div class="form-check">
                                <input type="radio" name="PaymentMethod" value="1" id="paymentVnPay" class="form-check-input">
                                <label class="form-check-label" for="paymentVnPay">VnPay</label>
                            </div>
                            <div class="form-check">
                                <input type="radio" name="PaymentMethod" value="2" id="paymentMomo" class="form-check-input">
                                <label class="form-check-label" for="paymentMomo">Momo</label>
                            </div>
                        </dd>
                        <dt class="col-sm-4 font-weight-bold">Trạng thái hóa đơn</dt>
                        <dd class="col-sm-8">
                            <span class="badge Trạng thái hóa đơn">@Model.Status</span>
                        </dd>
                        <dt class="col-sm-4 font-weight-bold">Nhân viên</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Cashier.FullName)</dd>
                        <dt class="col-sm-4 font-weight-bold">Ghi chú</dt>
                        <dd class="col-sm-8">
                            <input name="Note" id="Note" placeholder="Nhập ghi chú..." class="form-control">
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="mt-4">
                <a class="btn btn-danger" asp-action="Details" asp-route-id="@Model.Id">Hoãn thanh toán</a>
                <button type="button" id="submitCheckout" class="btn btn-primary">Xác nhận</button>
            </div>
        </div>
    </div>
</div>
<div id="Fields" class="container-fluid px-5 mt-4">
    <div class="card">
        <div class="card-header bg-success text-white">
            <h4 class="mb-0">Sân sử dụng</h4>
        </div>
        <div class="card-body">
            <table class="table table-striped table-hover table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>Tên sân</th>
                        <th>Loại sân</th>
                        <th>Giá sân</th>
                        <th>Bắt đầu</th>
                        <th>Kết thúc</th>
                        <th>Thành tiền</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        double allcost = 0;
                    }
                    @foreach (var item in Model.Fields)
                    {
                        allcost +=(double) item.Cost;
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Name)</td>
                            <td>@Html.DisplayFor(modelItem => item.Type)</td>
                            <td>
                                @string.Format("{0:#,0}", item.Price)
                                @if (Model.Booking.RentalType == 0)
                                {
                                    @: đ/giờ
                                }
                                else
                                {
                                    @: đ/Tháng
                                }
                            </td>
                            <td>@Html.DisplayFor(modelItem => item.Start)</td>
                            <td>@Html.DisplayFor(modelItem => item.End)</td>
                            <td>@string.Format("{0:#,0}", item.Cost)</td>
                        </tr>
                    }
                    <tr class="font-weight-bold">
                        <th colspan="5" class="text-right">Tổng cộng</th>
                        <th>@string.Format("{0:#,0}đ", allcost)</th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="container-fluid px-5 mt-4">
    <div class="card">
        <div class="card-header bg-primary text-white">
            <h4 class="mb-0">Dịch vụ đã sử dụng</h4>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th>Mã dịch vụ</th>
                        <th>Tên dịch vụ</th>
                        <th>Loại dịch vụ</th>
                        <th>Giá</th>
                        <th>Số lượng</th>
                        <th>Thành tiền</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        double total = 0;
                    }
                    @foreach (var item in Model.Order)
                    {
                        total += item.InvoiceService.Quantity * item.Price;
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.InvoiceService.Service.Id)</td>
                            <td>@Html.DisplayFor(modelItem => item.InvoiceService.Service.Name)</td>
                            <td>@Html.DisplayFor(modelItem => item.InvoiceService.Service.Type)</td>
                            <td>@string.Format("{0:#,0}đ", item.Price)</td>
                            <td>@Html.DisplayFor(modelItem => item.InvoiceService.Quantity)</td>
                            <td>@string.Format("{0:#,0}đ", item.Price * item.InvoiceService.Quantity)</td>
                        </tr>
                    }
                    <tr class="font-weight-bold">
                        <th colspan="5" class="text-right">Tổng cộng</th>
                        <th>@string.Format("{0:#,0}đ", total)</th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#submitCheckout').on('click', function () {
                console.log('error')
                var id = '@Model.Id';
                var note = $('#Note').val();
                var paymentMethod = $('input[name="PaymentMethod"]:checked').val();

                $.ajax({
                    url: '@Url.Action("Checkout", "Invoice")',
                    type: 'POST',
                    data: {
                        id: id,
                        pm: paymentMethod,
                        note: note
                    },
                    success: function (result) {
                        window.location.href = result.redirectUrl;
                    },
                    error: function (error) {
                        console.error('Error during checkout:', error);
                    }
                });
            });
        });
    </script>

DemoSanBong/Views/Invoice/Index.cshtml
@model IEnumerable<DemoSanBong.ViewModels.BookingViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<link rel="stylesheet" href="~/css/Invoice.css"/>

<div class="container">
    <h1>Danh sách <span class="highlight">Đặt sân</span></h1>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Mã đặt sân
                </th>
                <th>
                    Tên khách hàng
                </th>
                <th>
                    Số điện thoại
                </th>
                <th>
                    Hình thức thuê
                </th>
                <th>
                    Ngày đặt
                </th>
                <th>
                    Trạng thái
                </th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Customer.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Customer.PhoneNumber)                        
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreateDate)
                    </td>
                    <td>
                        @item.State
                    </td>
                    <td>
                        <a class="btn btn-info" asp-action="Check" asp-route-id="@item.Id">Kiểm tra</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>